// =============================================================================
// src/lib/db.ts — Lightweight typed DB client using pg directly
//
// WHY THIS FILE EXISTS:
//   Prisma 5 requires downloading native binaries (~50MB) from binaries.prisma.sh
//   during `prisma generate`. In restricted environments (CI, air-gapped, demo
//   setups), this download fails. This module provides a zero-dependency-download
//   database layer using the `pg` npm package (pure JS, no binary downloads).
//
// DESIGN:
//   - Same RLS pattern: every query sets SET LOCAL app.current_tenant = <uuid>
//   - TypeScript types from our own contracts (not generated by Prisma)
//   - Full tenant isolation maintained — same security guarantees
//   - Prisma schema still used for migrations (prisma migrate works standalone)
//
// USAGE:
//   const db = getDb()
//   const result = await db.query<Patient>('SELECT * FROM patients WHERE id = $1', [id])
//   await db.withTenant(tenantId, async (client) => {
//     const rows = await client.query('SELECT * FROM patients', [])
//   })
// =============================================================================

import { Pool, PoolClient, QueryResult, QueryResultRow } from 'pg'

// ─────────────────────────────────────────────────────────────────
// Connection pool singleton
// ─────────────────────────────────────────────────────────────────

const globalDb = globalThis as unknown as { _pgPool?: Pool }

function getPool(): Pool {
  if (!globalDb._pgPool) {
    const connString = process.env.DATABASE_URL
    if (!connString) throw new Error('DATABASE_URL environment variable is not set')

    globalDb._pgPool = new Pool({
      connectionString: connString,
      max: 20,
      idleTimeoutMillis: 30_000,
      connectionTimeoutMillis: 5_000,
      ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized: false } : false,
    })

    globalDb._pgPool.on('error', (err) => {
      console.error('[DB] Pool error:', err.message)
    })
  }
  return globalDb._pgPool
}

// ─────────────────────────────────────────────────────────────────
// UUID validation — prevent SQL injection before setting tenant context
// ─────────────────────────────────────────────────────────────────

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i

function assertUUID(value: string, field: string): void {
  if (!UUID_RE.test(value)) {
    throw new Error(`Invalid UUID format for ${field}: "${value}"`)
  }
}

// ─────────────────────────────────────────────────────────────────
// Tenant-scoped query executor
// Every query runs inside a transaction with RLS context set
// ─────────────────────────────────────────────────────────────────

export interface TenantClient {
  query<T extends QueryResultRow = QueryResultRow>(
    sql: string,
    params?: unknown[]
  ): Promise<QueryResult<T>>

  queryOne<T extends QueryResultRow = QueryResultRow>(
    sql: string,
    params?: unknown[]
  ): Promise<T | null>

  queryMany<T extends QueryResultRow = QueryResultRow>(
    sql: string,
    params?: unknown[]
  ): Promise<T[]>

  execute(sql: string, params?: unknown[]): Promise<void>
  tenantId: string
}

export async function withTenant<T>(
  tenantId: string,
  fn: (client: TenantClient) => Promise<T>
): Promise<T> {
  assertUUID(tenantId, 'tenantId')

  const pool = getPool()
  const pgClient = await pool.connect()

  try {
    await pgClient.query('BEGIN')
    // SET LOCAL: scoped to this transaction only — cleans up on commit/rollback
    await pgClient.query(`SET LOCAL app.current_tenant = '${tenantId}'::uuid`)

    const tc: TenantClient = {
      tenantId,
      async query<T extends QueryResultRow>(sql: string, params?: unknown[]) {
        return pgClient.query<T>(sql, params)
      },
      async queryOne<T extends QueryResultRow>(sql: string, params?: unknown[]): Promise<T | null> {
        const result = await pgClient.query<T>(sql, params)
        return result.rows[0] ?? null
      },
      async queryMany<T extends QueryResultRow>(sql: string, params?: unknown[]) {
        const result = await pgClient.query<T>(sql, params)
        return result.rows
      },
      async execute(sql: string, params?: unknown[]) {
        await pgClient.query(sql, params)
      },
    }

    const result = await fn(tc)
    await pgClient.query('COMMIT')
    return result
  } catch (err) {
    await pgClient.query('ROLLBACK')
    throw err
  } finally {
    pgClient.release()
  }
}

// ─────────────────────────────────────────────────────────────────
// Raw pool access — for auth (pre-tenant context) and health checks
// ─────────────────────────────────────────────────────────────────

export function getDb() {
  return {
    pool: getPool(),

    // Health check — no tenant context needed
    async ping(): Promise<boolean> {
      try {
        const client = await getPool().connect()
        await client.query('SELECT 1')
        client.release()
        return true
      } catch {
        return false
      }
    },

    // Raw query without tenant context (for auth, migrations, checks)
    async rawQuery<T extends QueryResultRow = QueryResultRow>(
      sql: string,
      params?: unknown[]
    ): Promise<QueryResult<T>> {
      return getPool().query<T>(sql, params)
    },
  }
}

// ─────────────────────────────────────────────────────────────────
// Audit log writer — always within caller's transaction
// ─────────────────────────────────────────────────────────────────

export async function writeAuditLog(
  client: TenantClient,
  params: {
    actorId?:     string
    actorRole?:   string
    resourceType: string
    resourceId:   string
    action:       string
    diff?:        object
    ipAddress?:   string
    userAgent?:   string
  }
): Promise<void> {
  await client.execute(
    `INSERT INTO audit_logs (
      id, "tenantId", "actorId", "actorRole", "resourceType",
      "resourceId", action, diff, "ipAddress", "userAgent", "occurredAt"
    ) VALUES (
      gen_random_uuid(), $1::uuid, $2, $3, $4, $5::uuid, $6, $7, $8, $9, NOW()
    )`,
    [
      client.tenantId,
      params.actorId   ?? null,
      params.actorRole ?? null,
      params.resourceType,
      params.resourceId,
      params.action,
      params.diff ? JSON.stringify(params.diff) : null,
      params.ipAddress ?? null,
      params.userAgent ?? null,
    ]
  )
}

// ─────────────────────────────────────────────────────────────────
// Graceful shutdown
// ─────────────────────────────────────────────────────────────────

export async function closeDb(): Promise<void> {
  if (globalDb._pgPool) {
    await globalDb._pgPool.end()
    delete globalDb._pgPool
  }
}

process.on('SIGTERM', closeDb)
process.on('SIGINT',  closeDb)
