// =============================================================================
// PreventiveScoreService
// Composite preventive health score (0–100, higher = healthier).
//
// Components:
//   1. cardiovascular (30%) — inverted Framingham 10yr risk
//   2. metabolic      (25%) — glucose, BMI, lipid ratios
//   3. biologicalAge  (25%) — delta from biophysics engine
//   4. lifestyle      (20%) — smoking, diabetes management, BP control
//
// Score is NOT a diagnostic tool. Positioned as "preventive orientation index".
// Human-in-the-loop: physicians review PENDING recommendations generated by
// DecisionEngine; this score does not trigger autonomous actions.
// =============================================================================

import { withTenant } from '../lib/db'
import { logger } from '../lib/logger'
import { getRedisClient } from '../lib/redis'

export interface PreventiveScoreResult {
  scoreId: string
  compositeScore: number   // 0–100
  scoreTier: ScoreTier
  components: {
    cardiovascular?: ComponentScore
    metabolic?: ComponentScore
    biologicalAge?: ComponentScore
    lifestyle?: ComponentScore
  }
  insufficientData: string[]
  computedAt: Date
  algorithmVersion: string
}

interface ComponentScore {
  score: number
  weight: number
  signals: string[]
}

type ScoreTier = 'OPTIMAL' | 'GOOD' | 'MODERATE_RISK' | 'HIGH_RISK' | 'CRITICAL'

const ALGORITHM_VERSION = 'preventive-composite-v1.0.0'
const CACHE_TTL = 4 * 60 * 60 // 4h

// ─────────────────────────────────────────────────────────────────

export class PreventiveScoreService {

  async computeForPatient(
    tenantId: string,
    patientId: string,
    correlationId: string
  ): Promise<PreventiveScoreResult | null> {
    const log = logger.child({ correlationId, tenantId, patientId, fn: 'PreventiveSvc' })

    // Load snapshot (Framingham inputs)
    const snapshot = await withTenant(tenantId, (tc) =>
      tc.queryOne(
        `SELECT * FROM patient_health_snapshots WHERE "tenantId"=$1::uuid AND "patientId"=$2::uuid`,
        [tenantId, patientId]
      )
    )

    // Load latest biophysics assessment
    const bioAge = await withTenant(tenantId, (tc) =>
      tc.queryOne(
        `SELECT "biologicalAge"::float, "differentialAge"::float, "ageAtSnapshot"
         FROM biological_age_assessments
         WHERE "tenantId"=$1::uuid AND "patientId"=$2::uuid AND "assessmentType"='BIOPHYSICS'
         ORDER BY "assessedAt" DESC LIMIT 1`,
        [tenantId, patientId]
      )
    )

    // Load latest Framingham risk score
    const riskScore = await withTenant(tenantId, (tc) =>
      tc.queryOne(
        `SELECT "valuePercent"::float, "riskCategory"
         FROM risk_scores
         WHERE "tenantId"=$1::uuid AND "patientId"=$2::uuid AND "scoreType"='CARDIOVASCULAR_10Y'
         ORDER BY "computedAt" DESC LIMIT 1`,
        [tenantId, patientId]
      )
    )

    const insufficientData: string[] = []
    const components: PreventiveScoreResult['components'] = {}
    let totalWeightedScore = 0
    let totalWeight = 0

    // ── Component 1: Cardiovascular (30%) ─────────────────────────
    if (riskScore) {
      const cvComponent = this.scoreCardiovascular(riskScore.valuePercent, riskScore.riskCategory)
      components.cardiovascular = { ...cvComponent, weight: 0.30 }
      totalWeightedScore += cvComponent.score * 0.30
      totalWeight += 0.30
    } else {
      insufficientData.push('cardiovascular_risk_score')
    }

    // ── Component 2: Metabolic (25%) ──────────────────────────────
    if (snapshot?.latestFastingGlucose || snapshot?.latestTotalCholesterol) {
      const metComponent = this.scoreMetabolic(snapshot)
      components.metabolic = { ...metComponent, weight: 0.25 }
      totalWeightedScore += metComponent.score * 0.25
      totalWeight += 0.25
    } else {
      insufficientData.push('metabolic_markers')
    }

    // ── Component 3: Biological Age (25%) ─────────────────────────
    if (bioAge && snapshot?.ageAtSnapshot) {
      const bioComponent = this.scoreBiologicalAge(
        bioAge.differentialAge,
        snapshot.ageAtSnapshot
      )
      components.biologicalAge = { ...bioComponent, weight: 0.25 }
      totalWeightedScore += bioComponent.score * 0.25
      totalWeight += 0.25
    } else {
      insufficientData.push('biological_age_assessment')
    }

    // ── Component 4: Lifestyle (20%) ──────────────────────────────
    if (snapshot) {
      const lifestyleComponent = this.scoreLifestyle(snapshot)
      components.lifestyle = { ...lifestyleComponent, weight: 0.20 }
      totalWeightedScore += lifestyleComponent.score * 0.20
      totalWeight += 0.20
    }

    // Need at least 2 components to produce a meaningful score
    if (totalWeight < 0.40) {
      log.warn({ totalWeight }, 'Insufficient data for composite score')
      return null
    }

    // Normalize to available weight (partial score when some components missing)
    const compositeScore = Math.round(totalWeightedScore / totalWeight)
    const scoreTier = this.classifyTier(compositeScore)

    const inputSnapshot = { snapshot, riskScore, bioAge }

    // Persist
    const scoreId = await this.persist(tenantId, patientId, compositeScore, scoreTier, components, inputSnapshot)

    // Cache
    await this.cache(tenantId, patientId, compositeScore)

    log.info({ compositeScore, scoreTier, componentsCount: Object.keys(components).length }, 'Preventive score computed')

    return {
      scoreId,
      compositeScore,
      scoreTier,
      components,
      insufficientData,
      computedAt: new Date(),
      algorithmVersion: ALGORITHM_VERSION,
    }
  }

  // ── Component scorers ─────────────────────────────────────────────

  private scoreCardiovascular(tenYearRiskPct: number, category: string): Omit<ComponentScore, 'weight'> {
    // Invert: 0% risk = 100 score, 30%+ risk = 0 score
    const score = Math.max(0, Math.round(100 - (tenYearRiskPct / 30) * 100))
    const signals: string[] = [`10yr_cvd_risk_${tenYearRiskPct.toFixed(1)}pct`, `category_${category.toLowerCase()}`]
    return { score, signals }
  }

  private scoreMetabolic(snapshot: Record<string, any>): Omit<ComponentScore, 'weight'> {
    let score = 100
    const signals: string[] = []

    const glucose = Number(snapshot.latestFastingGlucose)
    const tc      = Number(snapshot.latestTotalCholesterol)
    const hdl     = Number(snapshot.latestHdlMgDl)
    const ldl     = Number(snapshot.latestLdlMgDl)

    if (glucose) {
      if (glucose >= 126)       { score -= 30; signals.push('glucose_diabetic_range') }
      else if (glucose >= 100)  { score -= 15; signals.push('glucose_prediabetes') }
      else                      { signals.push('glucose_normal') }
    }

    if (ldl) {
      if (ldl >= 190)           { score -= 25; signals.push('ldl_severely_elevated') }
      else if (ldl >= 160)      { score -= 15; signals.push('ldl_elevated') }
      else if (ldl >= 130)      { score -= 5;  signals.push('ldl_borderline') }
      else                      { signals.push('ldl_optimal') }
    }

    if (hdl) {
      if (hdl < 40)             { score -= 10; signals.push('hdl_low') }
      else if (hdl >= 60)       { score += 5;  signals.push('hdl_protective') } // bonus
    }

    if (tc && hdl) {
      const ratio = tc / hdl
      if (ratio > 5)            { score -= 10; signals.push('tc_hdl_ratio_high') }
    }

    return { score: Math.max(0, Math.min(100, score)), signals }
  }

  private scoreBiologicalAge(differentialAge: number, _chronoAge: number): Omit<ComponentScore, 'weight'> {
    // -10 to +10 year range maps to 0–100
    // delta -10 = score 100 (very rejuvenated), delta +10 = score 0
    const score = Math.max(0, Math.min(100, Math.round(50 - differentialAge * 5)))
    const signals: string[] = [
      `bio_age_delta_${differentialAge > 0 ? '+' : ''}${differentialAge.toFixed(1)}yr`,
      differentialAge <= -2 ? 'rejuvenecido' : differentialAge >= 2 ? 'envejecido' : 'normal',
    ]
    return { score, signals }
  }

  private scoreLifestyle(snapshot: Record<string, any>): Omit<ComponentScore, 'weight'> {
    let score = 100
    const signals: string[] = []

    if (snapshot.isSmoker === true)            { score -= 25; signals.push('smoker') }
    else if (snapshot.isSmoker === false)      { signals.push('non_smoker') }

    if (snapshot.hasDiabetes === true)         { score -= 15; signals.push('diabetes_diagnosed') }

    if (snapshot.isOnAntihypertensives === true) {
      // On meds = managed (positive signal vs. unmanaged hypertension)
      const systolic = Number(snapshot.latestSystolicBp)
      if (systolic >= 140) { score -= 10; signals.push('hypertension_uncontrolled') }
      else                 { score -= 5;  signals.push('hypertension_managed') }
    }

    return { score: Math.max(0, score), signals }
  }

  // ── Persistence ────────────────────────────────────────────────────

  private async persist(
    tenantId: string,
    patientId: string,
    compositeScore: number,
    scoreTier: ScoreTier,
    components: PreventiveScoreResult['components'],
    inputSnapshot: unknown
  ): Promise<string> {
    const row = await withTenant(tenantId, (tc) =>
      tc.queryOne(
        `INSERT INTO preventive_scores (
           id, "tenantId", "patientId",
           "compositeScore", "scoreTier",
           "cardiovascularScore", "metabolicScore", "biologicalAgeScore", "lifestyleScore",
           "inputSnapshot", "algorithmId", "algorithmVersion", "computedAt"
         ) VALUES (
           gen_random_uuid(), $1::uuid, $2::uuid,
           $3, $4, $5, $6, $7, $8,
           $9::jsonb, 'preventive-composite', $10, NOW()
         ) RETURNING id`,
        [
          tenantId, patientId,
          compositeScore, scoreTier,
          components.cardiovascular?.score ?? null,
          components.metabolic?.score ?? null,
          components.biologicalAge?.score ?? null,
          components.lifestyle?.score ?? null,
          JSON.stringify(inputSnapshot),
          ALGORITHM_VERSION,
        ]
      )
    )
    return row.id
  }

  private async cache(tenantId: string, patientId: string, score: number) {
    try {
      const redis = getRedisClient()
      await redis.setex(`preventive:${tenantId}:${patientId}:score`, CACHE_TTL, String(score))
    } catch (_) { /* non-fatal */ }
  }

  private classifyTier(score: number): ScoreTier {
    if (score >= 80) return 'OPTIMAL'
    if (score >= 60) return 'GOOD'
    if (score >= 40) return 'MODERATE_RISK'
    if (score >= 20) return 'HIGH_RISK'
    return 'CRITICAL'
  }
}
